name: 4testing multiarch-cron-build


on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Action
        env:
          REPO_NAME: DocSpace-buildtools
        run: |
          curl -X POST -u "${{ secrets.USERNAME}}:${{secrets.TOKEN}}" \
          "https://api.github.com/repos/lemmav/DocSpace-buildtools/dispatches" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          --data '{"event_type": "cron-trigger-action"}'